import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { ToastifyProvider } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <link rel="icon" href="/favicon.png" />
      <UserProvider>
        <body className={inter.className}>
          <ToastifyProvider>{children}</ToastifyProvider>
        </body>
      </UserProvider>
    </html>
  );
}
