import { Metadata } from "next";
import Image from "next/image";
import "./main.module.css";
import { PricingSection } from "./components";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Mesa Facil - Inicio",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

export default async function Home() {
  return (
    <main className="min-h-screen">
      <header className="border-b flex justify-between items-center px-5">
        <div className="flex gap-3 items-center ">
          <h1 className="text-3xl font-bold text-center text-orange-">
            Mesa <br /> Facil
          </h1>
          <div
            style={{
              position: "relative",
              width: "100px",
              height: "100px",
              filter: "brightness(1.1)",
              mixBlendMode: "multiply",
            }}
          >
            <Image src="/logo2.jpg" alt="Mesa Facil" sizes="100px" fill />
          </div>
        </div>
        <nav>
          <ul className="flex gap-3">
            <li>
              <Link href="/api/auth/login">Login</Link>
            </li>
            <li>
              <Link href="/api/auth/login">Registro</Link>
            </li>
          </ul>
        </nav>
      </header>
      <section className="flex flex-col justify-center itesm-center py-10">
        <div className="mx-auto max-w-screen-md text-center mb-8 lg:mb-12">
          <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:">
            Reservar una mesa nunca fue tan facil
          </h2>
          <p className="mb-5 font-light text-gray-500 sm:text-xl ">
            Mesa Facil es una aplicación que te permite reservar una mesa en tu
            restaurante favorito. Empezá gratis hoy mismo.
          </p>
        </div>
        <div className="flex justify-center align-center">
          <div className="px-10 flex flex-col justify-center  items-center gap-3 bg-[#f2f2f2b3] rounded-xl max-w-[600px]">
            <div className="flex flex-col gap-3">
              <h2 className="text-2xl font-semibold text-center">
                ¿Que es Mesa Facil? 🤔
              </h2>
              <p>
                Mesa Facil es una aplicación que te permite reservar una mesa en
                tu restaurante favorito.
              </p>
            </div>
            <div className="flex flex-col gap-3">
              <h2 className="text-2xl font-semibold text-center">
                ¿Como funciona? 🍽️
              </h2>
              <p>
                Mesa Facil es una aplicación que te permite reservar una mesa en
                tu restaurante favorito.
              </p>
            </div>

            <div className="flex flex-col gap-3">
              <h2 className="text-2xl font-semibold text-center">
                Quiero ser parte de Mesa Facil 🤩
              </h2>
              <p>
                Para ser parte de Mesa Facil, solo debes registrarte en nuestra
                plataforma. Conocé más en nuestra sección de registro.
              </p>
            </div>
          </div>
          <div
            style={{
              position: "relative",
              width: "400px",
              height: "400px",
              filter: "brightness(1.1)",
              mixBlendMode: "multiply",
            }}
          >
            <Image src="/logo2.jpg" alt="Mesa Facil" sizes="400px" fill />
          </div>
        </div>
      </section>
      {/*section banner with prices*/}
      <section className="bg-orange-roughy-200 w-full">
        <PricingSection />
      </section>
    </main>
  );
}
